# this is try catch excetion example 
try :
    Age = int(input("Age : "))
    print(Age)
except ValueError:
    print("Invalid Value Passed")